language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - add-on
  - extra
licenses:
- android-sdk-license-.+
before_install:
- echo $TRAVIS_BUILD_NUMBER
- yes | sdkmanager "platforms;android-29"
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
- chmod +x .travis/build.sh
script:
#- "./gradlew assembleRelease"
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew assembleRelease; fi'
- .travis/build.sh
before_deploy:
  - echo gitVersion
  - git rev-list --all --count
  - echo version
  - git describe --tags
  - echo $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: jTKF+LORoR5pXPd5XsVoRgtlx0vqMN8wuvuH680KT/AgrFh2usKIaBCUmM2KYYnwbnxT5lm5eX58lr22mVAn0OzajBGhiilWpQuoDcI3aU0vfki7awFILq/n3tnMvewtz4b89w9dDKPFz/AEdBd1W5gDr/y8A4VLpi6n7n8GPdq/8rk0LHJSxsgKVN9hpzXNBgDCxt2AzH20ZFcUaN7mgVbiL+cQC/9r+zNLkhBqph8TFGU//L+P5mbpVSvd2zJZHwJ27WGeWM5sndgilXEFi2HYVR/mJxqiVLqlnpI9i+e7TzRUoEcuWW8+UcDz4XcCOGMZFjNPgbT1kXwusNKrLU1Dh81qeseeFVZuGgA0DIXczvDTG/U/B4GMT3rIXL6W9eow+J8upZ4WfWkZe6gp57SpBt+FS5bqoiIN/pSp8Bur/NH2hVoCIYpReQ/8l43LF2EfgHSUibiPDiZpsHcihmZ5oZqXb4sxDEy6Rd4pVPr3BD54O46NYcjyATsLoCRI9IU4xEwv1W+Etw4FarMAW80AiS232X4B4MnQ7nm83BZkSI5/YbeqB5yOvK7jCwRoZCdQFUPmOWRC3sVTbNDlRdiY2oJWtE8WoiEIG3GIm/Qy+/9WyGmEuNb7BIy3PGlBEhzTbT//BXh06PJfg9+IkocecJrgTBNXOLkZPYO+BKs=
  file:
  - ApkInfo.json
  - app/build/outputs/apk/release/Cimoc*.apk
  file_glob: true
  on:
    repo: Haleydu/Cimoc
    branch: release-tci
    tags: true
  skip_cleanup: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ecc6bd870c911bd6222
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
